// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqivJ4YDKD1Umavu1J9q0gkzIEK0aFACk',
    appId: '1:472779404725:web:13a3c39bde3db1892115fc',
    messagingSenderId: '472779404725',
    projectId: 'shiftwheels-8019f',
    authDomain: 'shiftwheels-8019f.firebaseapp.com',
    storageBucket: 'shiftwheels-8019f.firebasestorage.app',
    measurementId: 'G-2QRBV15XKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx3ZW6YP4_-T0NeoYjAxdiyKQgn6tr_lw',
    appId: '1:472779404725:android:6f1d0c6af838fa272115fc',
    messagingSenderId: '472779404725',
    projectId: 'shiftwheels-8019f',
    storageBucket: 'shiftwheels-8019f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAHOdtl1Q0StKXznfc46NhlnVdpoW70KA',
    appId: '1:472779404725:ios:4aa79b27d55452542115fc',
    messagingSenderId: '472779404725',
    projectId: 'shiftwheels-8019f',
    storageBucket: 'shiftwheels-8019f.firebasestorage.app',
    iosBundleId: 'com.abhijith.shiftwheels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqivJ4YDKD1Umavu1J9q0gkzIEK0aFACk',
    appId: '1:472779404725:web:94d4a4097760ca872115fc',
    messagingSenderId: '472779404725',
    projectId: 'shiftwheels-8019f',
    authDomain: 'shiftwheels-8019f.firebaseapp.com',
    storageBucket: 'shiftwheels-8019f.firebasestorage.app',
    measurementId: 'G-C01Y501DYC',
  );
}
